const CONTENT = {

  clues: {
    "I-01": { beat: 1, tag: "TIME", title: "Every clock reads 9:14:00",
      means: "Time stopped with the Sun. Not a fade — a stop. Every clock in the world is on the same second, and nobody is moving it.",
      where: "Apprentice Annex, wall clock",
      reacts: "No one — not yet. Ray simply accepts it.",
      unlocks: "Sets the clock running for the whole game." },
    "I-06": { beat: 1, tag: "SUNWRITING", title: "9:14, written on the wall",
      means: "Sunwriting only renders where the light is agreed upon. Someone stood here, agreed light with this mark, and wrote the time of the crime down so a later person would find it in the first thirty seconds.",
      where: "Apprentice Annex, far wall (held beam)",
      quote: "9:14",
      reacts: "Ray writes it in his notebook. He does not know why he is writing it.",
      unlocks: "The most important clue in the game, and it is never explained." },
    "I-04": { beat: 1, tag: "LOGBOOK", title: "Page twelve, signed by Ray",
      means: "Eleven entries, then a hard black block. Ray signs the blank page without reading it. Later, in the Control Room, he will find that same page waiting for him.",
      where: "Apprentice Annex, lectern logbook",
      reacts: "Ray — later, on the tape, in his own handwriting.",
      unlocks: "The replay payoff. The tutorial's most casual line is the reveal's foundation." },
    "I-05": { beat: 1, tag: "SCENE", title: "The mirror, already angled",
      means: "Nobody sets a mirror like that. Ray adjusted it twenty minutes before the crash, to the exact position he will need to reproduce a message on a wall — and never thought about it again.",
      where: "Apprentice Annex, swivel stand",
      reacts: "\"Why's the mirror like that? Nobody sets a mirror like that.\"",
      unlocks: "The required geometry for the reconstruction puzzle." },
    "I-02": { beat: 1, tag: "SCENE", title: "Certificate plate: RAY",
      means: "Ray was certified to operate the Sun Control switch. Months ago. He certified himself in case this exact day came.",
      where: "Apprentice Annex, wall plaque",
      reacts: "No one.",
      unlocks: "Why Ray was allowed through the Control Room door." },
    "D-02": { beat: 2, tag: "PHYSICAL", title: "A bulb that blew outward",
      means: "Not a power cut. A push. Something shoved the power out of the street from the outside, and everything on the grid took it in the face.",
      where: "Dark Street, lamppost",
      reacts: "Wick: \"Correct. Finally.\"  Sir: pops toast.",
      unlocks: "The east/west thesis." },
    "S-01": { beat: 3, tag: "TESTIMONY", title: "Every shadow swung east",
      means: "The light didn't fade, it left. A hundred thousand shadows swung east at once, which means a hundred thousand people turned toward the Sun Control Facility.",
      where: "The Moon",
      reacts: "The Moon: \"Toward where the light was. Shadows point at the thing you lost.\"",
      unlocks: "Direction of origin." },
    "S-03": { beat: 3, tag: "PHYSICAL", title: "A photograph, burnt into bread",
      means: "The surge, imaged. Torch on the toast face and the burn isn't damage — it's a photograph of an electrical event entering from the right. Same direction as the shadows.",
      where: "Burnt Kitchen, Sir",
      reacts: "Ray: \"the bread did the only honest thing available to it.\"",
      unlocks: "Confirms the push came from the east." },
    "S-04": { beat: 3, tag: "PHYSICAL", title: "The old pale slice",
      means: "Eleven days old, and barely burned. Sir has kept the first one. There was an event before this one — there were two.",
      where: "Burnt Kitchen, Sir's drawer",
      quote: "one per day, eleven days, each one worse",
      reacts: "Marlow, in Beat 4: \"I did it for four seconds.\"",
      unlocks: "The false solution, and the counter." },
    "V-02": { beat: 4, tag: "COUNTER", title: "The counter reads 2",
      means: "Two events. Marlow only ever accounts for one. Someone finished what he started.",
      where: "Marlow's workshop, switch replica",
      reacts: "Marlow: \"It won't take my light.\"",
      unlocks: "The signature, and the reason Marlow is innocent." },
    "V-03": { beat: 4, tag: "SIGNATURE", title: "TECH 4 / MARLOW — and CD-19",
      means: "The first authorisation is oxidised and eleven days old. The second is sharp and new. TECH 4 is Marlow. CD-19 is a badge number, and it is fresh.",
      where: "Marlow's workshop, switch replica (held beam)",
      reacts: "Ray: \"That's not a real name, Marlow.\" — and walks away.",
      unlocks: "Ray's own badge number." },
    "N-01": { beat: 5, tag: "GLYPHS", title: "Four numbered shapes",
      means: "Not letters. Someone didn't want this read by anyone who'd recognise the alphabet. Triangle, circle, bar, dot — in that order.",
      where: "Facility gate receivers (held beam)",
      reacts: "The gate, which light opens and only light opens.",
      unlocks: "Access to the Lamp Vault." },
    "F-01": { beat: 6, tag: "TIMESTAMP", title: "9:13:41",
      means: "Nineteen seconds before the world ended, a man badged into the Lamp Vault. Lumen saw him. She will not say his name.",
      where: "Lamp Vault",
      reacts: "Lumen.",
      unlocks: "The last nineteen seconds." },
    "F-03": { beat: 6, tag: "PHYSICAL", title: "Counter 2, CD-19, a fresh thumbprint",
      means: "The real switch. Same two events, same badge — and a thumbprint made this morning. \"That's my thumb. I'd know it anywhere. That's a terrible thing to be able to say.\"",
      where: "Sun Control Room (held beam)",
      reacts: "Ray, without flinching.",
      unlocks: "Everything." },
    "F-04": { beat: 6, tag: "DOCUMENT", title: "The access log tape",
      means: "Paper, because Ray's design made every other system unnecessary. Sunwriting. Ray's handwriting. Addressed to Ray.",
      where: "Sun Control Room",
      quote: "HELLO, RAY. IF YOU ARE READING THIS, I HAVE FORGOTTEN, AND YOU WILL WANT TO KNOW WHY. — R.",
      reacts: "\"That's my handwriting, and I wrote it, and I don't remember writing it.\"",
      unlocks: "The motive, and the ending puzzle." },
    "Z-01": { beat: 7, tag: "RULE", title: "Custody Transfer",
      means: "A shutdown holds only while a case is open. It releases when the case is closed by a detective with no memory of closing it. Ray read this at 9:13:48 and understood the price.",
      where: "Sun Control Room, panel",
      quote: "IT RELEASES WHEN THE CASE IS CLOSED BY A DETECTIVE WITH NO MEMORY OF CLOSING IT.",
      reacts: "Ray: \"Ah. Ah, no.\"",
      unlocks: "The notebook connection." },
    "Z-02": { beat: 7, tag: "SUNWRITING", title: "The rest of the wall",
      means: "The message Ray left his forgotten self, completed by the light path he trained himself to build forty minutes ago.",
      where: "Apprentice Annex, far wall (reconstruction)",
      quote: "IT IS NOT A TRICK. THE CASE HAS TO BE CLOSED BY SOMEONE WHO DID NOT CLOSE IT. I AM SORRY. ALSO LINE TWELVE IS STILL ON THE WALL. USE THE LIGHT.",
      reacts: "Ray, reading his own apology aloud.",
      unlocks: "The ending." },
    "F-05": { beat: 7, tag: "WITHHELD", title: "Log Entry 914, line twelve",
      means: "The reason for all of it. Blacked out. Never read by the player. Never read by Ray. It stays black.",
      where: "Sun Control Room, logbook",
      reacts: "Nothing. That is the point.",
      unlocks: "Nothing. Deliberately. This is the ending's restraint." }
  },

  people: {
    "moon":  { name: "THE MOON", role: "WITNESS · CORNER",
      say: "Yes. No. That is the entire event. Please stop walking around it.",
      lock: "" },
    "wick":  { name: "MR. WICK", role: "TALKING LAMP · SHOP",
      say: "Precisely what has been pointed at me. People think that because I'm on, I see.",
      lock: "" },
    "sir":   { name: "SIR", role: "TOASTER · DINER",
      say: "▪▪▪▪▪ (pops toast)",
      lock: "" },
    "clouds":{ name: "THE CLOUDS", role: "WITNESS · ABOVE",
      say: "We were told to hold. The man who was already up there.",
      lock: "" },
    "marlow":{ name: "MARLOW", role: "THE VILLAIN",
      say: "I DIDN'T DO IT.",
      lock: "" },
    "lumen": { name: "LUMEN", role: "SECOND LAMP · VAULT",
      say: "You have not asked me properly once.",
      lock: "" },
    "locked":{ name: "—", role: "UNKNOWN",
      say: "Not yet.", lock: "locked" }
  },

  know: [
    { text: "9:14", glow: true },
    { text: "Something pushed it. Something east. It happened twice." },
    { text: "It was me.", glow: true }
  ],

  chips: [
    { id: "sig", label: "SIGNATURE · CD-19",
      pairs: { hand: "A signature and my handwriting. That's not a coincidence, that's a *policy*.",
               cnt:  "Somebody finished what Marlow started, and they had to sign for it." } },
    { id: "hand", label: "HANDWRITING · MINE",
      pairs: { sig: "A signature and my handwriting. That's not a coincidence, that's a *policy*.",
               cnt:  "I knew about one of these. I wrote down one of these and then I forgot it." } },
    { id: "cnt", label: "COUNTER · 2",
      pairs: { sig: "Somebody finished what Marlow started, and they had to sign for it.",
               hand: "I knew about one of these. I wrote down one of these and then I forgot it." } }
  ],

  tape: "HELLO, RAY.\nIF YOU ARE READING THIS, I HAVE FORGOTTEN,\nAND YOU WILL WANT TO KNOW WHY.\n\n— R.",

  endLines: ["ENTRY 914 … COMPLETE", "WITNESS … NONE", "LINE 12 …"],

  beats: {
    1: [
      { t: "thought", s: "Nine fourteen. Every clock says nine fourteen." },
      { t: "thought", s: "So the Sun is gone, and they gave the job to me, and let's be clear who's winning here. I am." },
      { t: "placard", head: "MODULE 1: LIGHT IS EVIDENCE",
        body: "TAKE THE LAMP IN YOUR HAND. IT IS NOT YOURS. TAKE IT ANYWAY." },
      { t: "thought", s: "Not mine. Sure. It's in my hand though, so there's a legal argument." },
      { t: "placard", head: "SWITCH BANK · A B C D",
        body: "THROW A AND B." },
      { t: "do", s: "throwA" },
      { t: "thought", s: "Nope." },
      { t: "do", s: "throwB" },
      { t: "thought", s: "A team. A and B. Of course. Why would a thing need a team." },
      { t: "placard", head: "THE MARK",
        body: "SUNWRITING IS INVISIBLE UNTIL THE LIGHT IS AGREED UPON. HOLD YOUR BEAM ON THE MARK." },
      { t: "objective", s: "Hold your beam on the mark" },
      { t: "waitMark" }
    ],
    reveal: [
      { t: "thought", s: "Nine fourteen. Yes. Everyone keeps saying nine fourteen." },
      { t: "thought", s: "Alright. Write it down, Ray." },
      { t: "clue", id: "I-06" },
      { t: "placard", head: "SWITCH BANK · A B C D",
        body: "THROW A AND B." },
      { t: "thought", s: "Might as well. Somebody will want it signed." },
      { t: "clue", id: "I-04" },
      { t: "thought", s: "Twelve pages and the twelfth is a lovely clean nothing. Somebody's idea of a joke." },
      { t: "objective", s: "Leave the Annex" },
      { t: "thought", s: "Right. Street, then people. People are easy — they have opinions and not one of them is evidence." },
      { t: "tape" },
      { t: "thought", s: "That's my handwriting." },
      { t: "thought", s: "That's my handwriting, and I wrote it, and I don't remember writing it." },
      { t: "objective", s: "Close the case" },
      { t: "openConnect" },
      { t: "waitConnect" }
    ]
  }
};

if (typeof module !== "undefined") module.exports = CONTENT;